[project]
name = "password-strength-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.44.0",
    "streamlit-option-menu>=0.4.0",
]
